language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  npm: true
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_install:
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
  - npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_KEY
before_script:
  - echo "Install the global requirements…"
  - yarn global add gatsby gh-pages
  - echo "Done installing."
after_success:
  - ./scripts/after_success.sh
stages:
  - build
  - name: deploy
    if: branch = master
jobs:
  include: 
    - stage: build
      name: "Build the project"
      script: yarn install
    - name: "Launch Storybook"
      script: yarn storybook
    - name: "Code Quality"
      script: yarn lint
    - name: "Unit Tests"
      script: yarn test
    - stage: deploy
      name: "Deploy the project"
      script: yarn deploy
