language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  npm: true
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_install:
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
  - npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_KEY
before_script:
  - echo "Building the project…"
  - yarn global add gatsby
  - yarn install
  - echo "Done building."
after_success:
  - ./scripts/after_success.sh
stages:
  - build
  - tests
  - name: deploy
    if: branch = master
jobs:
  include: 
    - stage: tests
      script: 
      - echo "Running tests…"
      - yarn lint
      - yarn test
      - echo "Done running tests."
    - stage: deploy
      script:
      - echo "Deploying to GitHub Pages…"
      - yarn global add gh-pages
      - yarn deploy
      - echo "Done deploying to GitHub Pages"
