language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_install:
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
  - npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_KEY
before_script:
  - "yarn global add gatsby"
  - "yarn global add gh-pages"
  - "yarn install"
script:
  - "yarn test"
after_success:
  - "yarn deploy"
